#spring.application.name=supplier
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/supplier
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true

#para quebrar as linhas do sql no logs
spring.jpa.properties.hibernate.format_sql=true

#Deixar de exibir o texto do "Strack Trace" no retorno da api.
server.error.include-stacktrace=never
#api.security.token.secret=${JWT_SECRET:12345678}